version: "3"

services:
  php:
    image: php:7.4-fpm
    container_name: twitCollect_php
    working_dir: /var/www
    restart: always
    volumes:
      - ./app:/var/www
    expose:
      - 9000
    
  webserver:
    image: nginx:latest
    container_name: twitCollect_webserver
    restart: always
    volumes:
      - ./app:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "10001:80"

